name: gfortran

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: ci
    if: github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/ci.yml

  integration-tests:
    name: ${{ matrix.toolchain.version }} ${{ matrix.image }} ${{
      matrix.toolchain.msystem }}
    if: github.actor != 'dependabot[bot]'
    runs-on: ${{ matrix.image }}
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        image:
          [
            windows-2025-vs2026,
          ]
        toolchain:
          - { compiler: gfortran, version: "16" }
          - { compiler: gfortran, version: "15" }
          - { compiler: gfortran, version: "14" }
          - { compiler: gfortran, version: "13" }
          - { compiler: gfortran, version: "12" }
          - { compiler: gfortran, version: "11" }
        include:
          - image: windows-2025-vs2026
            toolchain: { compiler: gfortran, msystem: ucrt64 } # only latest version available from Pacman
    steps:
      - uses: actions/checkout@v6

      - name: Restore dist-tests
        uses: actions/download-artifact@v8
        with:
          name: generated-dist-tests
          path: dist-tests

      - name: Install ${{ matrix.toolchain.compiler }} ${{ matrix.toolchain.version }}
        id: setup
        uses: ./
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
          msystem: ${{ matrix.toolchain.msystem }}

      - name: Verify installed version
        run: 'echo "Output: ${{ steps.setup.outputs.version }}"'

      - name: Run Integration Tests
        run: npm run integration-test
